In [175]:
import pandas as pd
import openpyxl

# 여러 줄 한번에 output 하기
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

df = pd.read_excel('C:/Users/dfocus/PycharmProjects/pythonProject/jupyter/가구수_test.xlsx', engine='openpyxl')

# 읍면동 제외
# df = df.loc[(df['행정구역별(시군구)'].s != '읍부') & (df['행정구역별(시군구)'] != '면부') & (df['행정구역별(시군구)'] != '동부')]

df = df.loc[(~df['행정구역별(시군구)'].str.contains('읍부')) & (~df['행정구역별(시군구)'].str.contains('면부')) & (~df['행정구역별(시군구)'].str.contains('동부'))]

df.reset_index(inplace=True, drop=True)

display(df)

      행정구역별(시군구) 가구주의 성별 가구주의 연령별                항목    년도        가구수
0          서울특별시       계       합계              일반가구  2016  3784705.0
1          서울특별시       계       합계          1세대가구-부부  2016   507729.0
2          서울특별시       계       합계   1세대가구-부부+미혼형제자매  2016     3947.0
3          서울특별시       계       합계    1세대가구-부부+기타친인척  2016      956.0
4          서울특별시       계       합계  1세대가구-가구주+미혼형제자매  2016    61817.0
...          ...     ...      ...               ...   ...        ...
32034    　　　서귀포시       계       합계  3세대가구-부부+미혼자녀+모친  2015     1480.0
32035    　　　서귀포시       계       합계          3세대가구-기타  2015     2157.0
32036    　　　서귀포시       계       합계          4세대이상 가구  2015      103.0
32037    　　　서귀포시       계       합계              1인가구  2015    15257.0
32038    　　　서귀포시       계       합계             비친족가구  2015     1047.0

[32039 rows x 6 columns]

In [176]:
print(type(df['행정구역별(시군구)']))

# str 형식은 *이 안된다.. 특수문자라 그런가??
df['시군구_TF']= pd.DataFrame(df['행정구역별(시군구)'].str.replace('　　　',' '))['행정구역별(시군구)'].str.count(' ')

df

<class 'pandas.core.series.Series'>

      행정구역별(시군구) 가구주의 성별 가구주의 연령별                항목    년도        가구수  시군구_TF
0          서울특별시       계       합계              일반가구  2016  3784705.0       0
1          서울특별시       계       합계          1세대가구-부부  2016   507729.0       0
2          서울특별시       계       합계   1세대가구-부부+미혼형제자매  2016     3947.0       0
3          서울특별시       계       합계    1세대가구-부부+기타친인척  2016      956.0       0
4          서울특별시       계       합계  1세대가구-가구주+미혼형제자매  2016    61817.0       0
...          ...     ...      ...               ...   ...        ...     ...
32034    　　　서귀포시       계       합계  3세대가구-부부+미혼자녀+모친  2015     1480.0       1
32035    　　　서귀포시       계       합계          3세대가구-기타  2015     2157.0       1
32036    　　　서귀포시       계       합계          4세대이상 가구  2015      103.0       1
32037    　　　서귀포시       계       합계              1인가구  2015    15257.0       1
32038    　　　서귀포시       계       합계             비친족가구  2015     1047.0       1

[32039 rows x 7 columns]

In [177]:
# str형
print(type(df.loc[0,'행정구역별(시군구)']))

arr = []

sido = '기본'

for i in range(0, len(df)):
    
#     print(df.loc[i,'시군구_TF'])

    if df.loc[i,'시군구_TF'] == 0 :
        
        sido = df.loc[i,'행정구역별(시군구)']
        
        arr.append(df.loc[i,'행정구역별(시군구)'])
        
    else:
        arr.append(sido + ' ' + df.loc[i,'행정구역별(시군구)'].replace('　　　',' '))


series = pd.Series(arr)

df['행정구역별(상세)'] = series

df

<class 'str'>

,행정구역별(시군구),가구주의 성별,가구주의 연령별,항목,년도,가구수,시군구_TF,행정구역별(상세)
0,서울특별시,계,합계,일반가구,2016,3784705.0,0,서울특별시
1,서울특별시,계,합계,1세대가구-부부,2016,507729.0,0,서울특별시
2,서울특별시,계,합계,1세대가구-부부+미혼형제자매,2016,3947.0,0,서울특별시
3,서울특별시,계,합계,1세대가구-부부+기타친인척,2016,956.0,0,서울특별시
4,서울특별시,계,합계,1세대가구-가구주+미혼형제자매,2016,61817.0,0,서울특별시
...,...,...,...,...,...,...,...,...
32034,서귀포시,계,합계,3세대가구-부부+미혼자녀+모친,2015,1480.0,1,제주특별자치도 서귀포시
32035,서귀포시,계,합계,3세대가구-기타,2015,2157.0,1,제주특별자치도 서귀포시
32036,서귀포시,계,합계,4세대이상 가구,2015,103.0,1,제주특별자치도 서귀포시
32037,서귀포시,계,합계,1인가구,2015,15257.0,1,제주특별자치도 서귀포시
32038,서귀포시,계,합계,비친족가구,2015,1047.0,1,제주특별자치도 서귀포시

In [178]:
df.to_csv('output.csv', index=False, encoding='euc-kr')